"""Initial migration

Revision ID: d4968d02f1e1
Revises: 
Create Date: 2023-11-14 23:47:32.607083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4968d02f1e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_id', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('area_sqkm', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('olympics',
    sa.Column('olympic_id', sa.String(length=7), nullable=False),
    sa.Column('country_id', sa.String(length=3), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.Column('enddate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('olympic_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('country_id', sa.String(length=3), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('eventtype', sa.String(length=20), nullable=True),
    sa.Column('olympic_id', sa.String(length=7), nullable=True),
    sa.Column('is_team_event', sa.Boolean(), nullable=True),
    sa.Column('num_players_in_team', sa.Integer(), nullable=True),
    sa.Column('result_noted_in', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['olympic_id'], ['olympics.olympic_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('results',
    sa.Column('event_id', sa.String(length=7), nullable=False),
    sa.Column('player_id', sa.String(length=10), nullable=False),
    sa.Column('medal', sa.String(length=7), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('events')
    op.drop_table('players')
    op.drop_table('olympics')
    op.drop_table('countries')
    # ### end Alembic commands ###
